# Generated by Django 5.1.7 on 2025-07-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_galleryimage_delete_gallaryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
