# Generated by Django 5.1.7 on 2025-08-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(default='img', upload_to='program_images/'),
        ),
    ]
