# Generated by Django 5.1.7 on 2025-08-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalmessage',
            name='image',
            field=models.ImageField(default='Image', upload_to=''),
        ),
    ]
