# Generated by Django 5.1.7 on 2025-08-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_principalmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='principal/'),
        ),
    ]
