# Generated by Django 5.1.7 on 2025-08-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_principalmessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principalmessage',
            name='image',
        ),
    ]
