# Generated by Django 5.2.4 on 2025-08-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vision',
            name='title',
        ),
    ]
